<?php
/**
 * Created by PhpStorm.
 * User: river
 * Date: 2016/4/21
 * Time: 20:02
 */

namespace PCPayClient\test\Entity;


use PCPayClient\Entity\PPToken;

class PPTokenTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @expectedException \PCPayClient\Entity\PPTokenException
     */
    public function testThrowException()
    {
        $token = "xl_LIAOPBf5C_566CmQbPPtDnbzfMBC8kUSopx3c";
        $tokenStr = '{"expired_in":28800,"expired_timestamp":'.(time() + (8 * 60 * 60)).'}';

        $token = new PPToken($tokenStr);
    }

    /**
     * @expectedException \PCPayClient\Entity\PPTokenException
     */
    public function testThrowException2()
    {
        $token = "xl_LIAOPBf5C_566CmQbPPtDnbzfMBC8kUSopx3c";
        $tokenStr = '{"token":"'.$token.'","expired_timestamp":'.(time() + (8 * 60 * 60)).'}';

        $token = new PPToken($tokenStr);
    }

    /**
     * @expectedException \PCPayClient\Entity\PPTokenException
     */
    public function testThrowException3()
    {
        $token = "xl_LIAOPBf5C_566CmQbPPtDnbzfMBC8kUSopx3c";
        $tokenStr = '{"token":"'.$token.'","expired_in":28800}';

        $token = new PPToken($tokenStr);
    }

    public function testProperties()
    {
        $token = "xl_LIAOPBf5C_566CmQbPPtDnbzfMBC8kUSopx3c";
        $expireIn = time() + (8 * 60 * 60);
        $tokenStr = '{"token":"'.$token.'","expired_in":28800,"expired_timestamp":'.$expireIn.'}';
        $tokenObj = new PPToken($tokenStr);

        $this->assertEquals($token, $tokenObj->getToken());
        $this->assertEquals($expireIn, $tokenObj->getExpireTimestamp());
        $this->assertEquals($tokenStr, $tokenObj->getJson());
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


}
